import os
from Typing import Callable
from Typing import Any
from src.flags import subcommands_options


def choose(items_to_be_choosen: list, **chosen_opts): ...
def confirm(prompt: str, **confirm_opts): ...
def file(path: str, **file_opts): ...
def filter(items_to_filter: list, **filter_opts): ...
def format(text: str, **format_opts): ...
def input(**input_opts): ...
def join(*strs, **join_opts): ...
def pager(filepath: str, **pager_opts): ...
def spin(fnc: Callable[..., Any], **spin_opts): ...
def style(text: str, **style_opts): ...
def table(filepath: str, **table_opts): ...
def write(**write_opts): ...
def log(text: str, **log_opts): ...
def version_check(**vc_opts): ...
